### ISSUE TITLE
Select boxes and Submit buttons broken on forms

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#34]
On any form with select boxes or submit buttons that aren't styled, they're broken.

This is especially problematic for select boxes as it took me a while to figure out why my project wasn't deploying until I realised the select box had no contents! :P

**Comment by asgrim** [comment]
I'll have a look at the select boxes anyway.

**Comment by asgrim** [comment]
Select boxes are fixed - just need submit buttons fixing. I believe that's just a case of missing images, AMIRITE?

**Comment by jonwigham** [comment]
That will be an issue, but the main thing is that we're using images for the submit buttons, so I changed the Abstract form class to look for Zend_Form_Element_Image rather than Zend_Form_Element_Sumit elements.

I'm going through some of the forms today, so I'll sort out the buttons as I go, but if you want them sorted in your repo asap, just change the elements to Zend_Form_Element_Image and call ->setImage() in the App_Form classes...
