### ISSUE TITLE
Absolute paths on FTP servers are broken

### ISSUE THREAD

**Issue by asgrim** [asgrim/godeploy#67]
If you put in a path such as dir/to/deployment/ the files upload in the correct place. This is fine with relative FTP directories, but sometimes people may wish to specify an absolute path e.g. /home/user/dir/to/deployment/

This is currently broken as the FTP test just uploads the test file to /home/user/.

**Comment by ghost** [comment]
Assuming this isn't being worked on I'll take it.

**Comment by ghost** [comment]
A bit of an update since I've been rather slow with this (been busy, honest!) - it seems to me this bug is caused by line 107 of GD_Ftp - an empty string will cause the function to return, and that means any absolute path will always return at that point because the first element of an absolute path split by "/" will naturally be "". Do you reckon a solution would be to check the array length and if its greater than 1, and the first element is empty, then the first element should be removed? That should give the same result as a relative path. I'll test this tommorow - going to watch Thor now :D

**Comment by ghost** [comment]
Sod it, i'll test it now like a good boy.

Edit - didn't have expected effect, will continue to test.

Edit 2 - changing line 112 of GD_ftp to "continue;" fixes this bug, but what do you think James?

**Comment by asgrim** [comment]
Something like that should work but I expect you'll have to `cd /` first to make sure you're at the root directory, and after what you suggested it should work. Basically, if an empty item is the first item (but not the last) then ignore it, but change directory to the root directory first.

**Comment by asgrim** [comment]
Try:

``` PHP
if($folders[$i] == "")
{
    if($i == 0)
    {
        $failed = false;
        while(ftp_pwd($this->_handle) != '/' && $failed = false)
        {
            $failed = ftp_cdup($this->_handle);
        }
        continue;
    }
    else
    {
        return true;
    }
}
```

**Comment by ghost** [comment]
Thanks for the help - that seems to do the trick. I've set up a pull request for it.

**Comment by asgrim** [comment]
Hmm I did a few other tests and got varying results. I've tweaked it a bit and it should work pretty universally now I hope.
